# Robot name goes here
newbot2:  # change the name
  # default controller
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
    extra_joints:
      - name: 'WFL_J'

      - name: 'WFR_J'


  # Controller left steering
  steering_controller: # change the name
    type: effort_controllers/JointPositionController # Type of controller. 
    joint: 'FL_J' # Name of the joint.  
    pid: {p: 100, i: 0.5, d: 10} # Enter your pid values eg. {p: 100.0 , i: 0.0 , d: 0.0} 

  # Controller right steering
  # FR_J_controller: # change the name
  #   type: effort_controllers/JointPositionController # Type of controller. 
  #   joint: 'FR_J' # Name of the joint.  
  #   pid: {p: 50, i: 0.5, d: 10} # Enter your pid values eg. {p: 100.0 , i: 0.0 , d: 0.0} 
  #
  
  # Controller for rear wheels WRL WRR
  driving_controller_rear:
    type: velocity_controllers/JointGroupVelocityController
    joints:
        - WRL_J
        - WRR_J
    pid_gains: 
        WRL_J: {p: 10, i: 1.0, d: 0.0}
        WRR_J: {p: 10, i: 1.0, d: 0.0}


 
